apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandbox-api-ingress
  namespace: sandbox
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: k8s.duginov.courses
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-service
                port:
                  number: 80
  tls:
    - hosts:
        - k8s.duginov.courses
      secretName: sandbox-api-tls