apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-job-access-binding
  namespace: sandbox
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sandbox
roleRef:
  kind: Role
  name: sandbox-job-access
  apiGroup: rbac.authorization.k8s.io